name: tests

on:
  push:
  schedule:
    - cron: "0 0 1 1 *" # Runs every January 1st at 00:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installing
        run: npm install
      - name: Testing
        run: npm test
        env:
          CI: true
